Repository gamifylab/react-ui, pull requests merged in 2023-10, with the labels that each got.

#3 Initial Settings
  .editorconfig
  .eslintignore
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  .prettierignore
  .prettierrc
  LICENSE
  commitlint.config.js
  package-lock.json
  package.json
Labels: settings

#6 StoryBook Initial Settings
  .eslintrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
Labels: enhancement, settings

#9 I18n Settings
  .storybook/decorators/i18n.tsx
  .storybook/preview.ts
  .storybook/preview.tsx
  locales/en.json
  locales/pt.json
  package-lock.json
  package.json
  src/App.tsx
  src/i18n.ts
  src/main.tsx
Labels: enhancement, settings

#15 Add Playwright Settings
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
Labels: enhancement, settings, test

#16 Add Testing Library
  package-lock.json
  package.json
Labels: enhancement, settings, test
